### PR TITLE
Exit with a non-zero code if the build failed

### LINKED ISSUE #70: Build returns succesfully despite failed push
On 0.0.24, he exit code of `builds:create` is 0 although the build failed (and is reported as such by Heroku):

```
-----> Python app detected
-----> Installing pip
 !     Push rejected, failed to compile Python app.

 !     Push failed
```

This causes the CI to wrongly believe deployment was successful.

### PR DESCRIPTION
**Pull request by dmathieu**
Closes #70

### CODE REVIEW

File: test/assert_exit.js [hunk 1]
```diff
@@ -0,0 +1,16 @@
+'use strict'
```
Comment (dmathieu) [inline test/assert_exit.js]: I've extracted this from [heroku-apps](https://github.com/heroku/heroku-apps/blob/master/test/assert_exit.js). It seems to be copied over in several plugins.
